version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lf_utils_postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  mssql:
    # image: mcr.microsoft.com/mssql/server:2022-latest
    # on macos we have two options: emulate the platform (slow) or use another image.
    # platform: linux/arm64
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: lf_utils_mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BetterUseP0stgres!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'BetterUseP0stgres!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  pgdata:
  mssqldata:
