name: "lf_utils_unit_tests"
version: "1.0"
config-version: 2

profile: 'lf_utils_duckdb'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt
    search_order: ['lf_utils_unit_tests', 'lf_utils', 'dbt']
  - macro_namespace: dbt_utils
    search_order: ['lf_utils_unit_tests', 'lf_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True

models:
  +bind: false
