# create env via:
# conda env create -f environment.yml -n my_env_name
name: dbt_playground
channels:
  - conda-forge
dependencies:
  - python=3.11.13
  # essentials
  - setuptools=80.9.0
  - wheel=0.45.1
  - numpy=2.3.2
  - scipy=1.16.1
  # database libs
  - pandas=2.3.1
  - polars=1.32.3
  - sqlalchemy=2.0.43
  # für unsere python cli tools benötigt
  - python-dotenv=1.1.1
  - typer=0.16.0
  # pip and dbt
  - pip=25.2
  - pip:
    # ms sql server adapter bisher nur kompatible mit dbt-core 1.9.*
    - dbt-core==1.9.8
    - dbt-duckdb==1.9.4
    - dbt-sqlserver==1.9.0
    - dbt-postgres==1.9.0
