# This workflow runs our dbt tests using DuckDB for every push and pull request on github.
name: DuckDB CI

on:
  push:
    branches: [ main, ps_early_prep ]
  pull_request:
    branches: [ main, ps_early_prep ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Create python venv with lf_py_stack
        run: |
            uv venv --python 3.12
            source .venv/bin/activate
            uv pip install git+https://github.com/linkFISH-Consulting/python-dbt-stack

      - name: Dbt deps
        run: |
            source .venv/bin/activate
            export DBT_PROJECT_DIR=./unit_tests
            dbt deps

      - name: Run dbt test
        run: |
          source .venv/bin/activate
          set -a; source config/.env.cicd; set +a
          mkdir -p $(dirname $LF_UTILS__DUCKDB_DATAMART_PATH)
          export DBT_PROFILE=lf_utils_duckdb
          export DBT_PROJECT_DIR=./unit_tests
          dbt debug
          dbt build
