# This workflow runs our dbt tests using DuckDB for every push and pull request on github.
name: DuckDB CI

on:
  push:
    branches: [ main, ps_early_prep ]
  pull_request:
    branches: [ main, ps_early_prep ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt dependencies
        run: |
          pip install dbt-duckdb
          dbt deps

      - name: Prepare environment variables
        run: |
          set -a
          source config/.env.cicd
          set +a
          export DBT_PROFILE=lf_utils_duckdb
          export DBT_TARGET=dev
          dbt build --select _dummy_source
          dbt test
