name: Postgres CI

on:
  push:
    branches: [ main, ps_early_prep ]
  pull_request:
    branches: [ main, ps_early_prep ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dbt-postgres
        run: pip install dbt-postgres

      - name: Wait for Postgres to be ready
        run: |
          set -a
          source config/.env.cicd
          set +a
          for i in {1..10}; do
            if pg_isready -h "$LF_UTILS__POSTGRES_HOST" -p "$LF_UTILS__POSTGRES_PORT" -U "$LF_UTILS__POSTGRES_USER"; then
              echo "Postgres is ready!"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 5
          done
          echo "Postgres did not become ready in time!" >&2
          exit 1
        env:
          PGPASSWORD: ${{ env.LF_UTILS__POSTGRES_PASSWORD }}

      - name: Run dbt test
        run: |
          set -a
          source config/.env.cicd
          set +a
          export DBT_PROFILE=lf_utils_postgres
          export DBT_TARGET=dev
          dbt build --select _dummy_source
          dbt test --vars '{"raise_on_error": false}'
